### PR TITLE
add Simplified Chinese support

### PR DESCRIPTION
**Pull request by pexcn**
There are some word I can not translate...

### CODE REVIEW

**Comment by MizzleDK** [comment]
Hi, thanks! Can you commit it against the branch called michell-dev?

**Comment by pexcn** [comment]
You mean the development branch is based on michell-dev?

**Comment by MizzleDK** [comment]
Yep, that's the development branch.

**Comment by pexcn** [comment]
Er......Ok, no problem~

**Comment by pexcn** [comment]
I need restart.....

**Pull request closed without merging**
